src/create-view-model.ts, test/create-view-model.js
hi! This PR should add support for maps and arrays. Let me know if it looks good or if I should remake something. 
Note the arrays cannot be modified in-place, but a new array has to be assigned to the viewModel, as it is done in tests. If it looks good, I'll add readme explanation before merge.
=> viewmodel support for maps and arrays

README.md
Found a minor typo/syntax error in README.md
=> Fixed Minor Typo in README.

CHANGELOG.md, README.md, package.json, src/from-promise.ts, src/tsconfig.json, test/from-promise.js, test/tsconfig.json, test/type-tests.ts
Fixes #56, #54, #53, #41, #45, #39
=> Improve `fromPromise`

.gitignore, CHANGELOG.md, README.md, package.json, src/async-action.ts, src/from-promise.ts, src/mobx-utils.ts, src/now.ts, src/tsconfig.json, test/async-action.ts, test/from-promise.js, test/tsconfig.json, test/type-tests.ts
=> Introduce `asyncAction` to support asynchronous actions that auto wrap `runInAction`

README.md
=> fix minor typo in documentation

README.md
ah didn't catch the other ones. fixed them too
=> fix other similar typos

src/create-view-model.ts
=> Export ViewModel class

src/create-view-model.ts, test/create-view-model.js
Fix for #100 
I'm not sure if using `_getAdministration` is a good idea 🤔
=> Add computed properties in view-model

package.json
fixed https://github.com/mobxjs/mobx-utils/issues/133
=> support webpack v4 sideEffects feature for enhanced tree shaking

CHANGELOG.md, src/create-transformer.ts, test/create-transformer.ts
=> fix createTransformer id collision

.travis.yml, CHANGELOG.md, package.json, src/async-action.ts, src/create-view-model.ts
1. add changelog and bump version according to https://github.com/mobxjs/mobx-utils/pull/137
2. update ci configuration & add lint stage
3. fix lint errors in source code
=> update ci configuration and changelog

README.md
=> fix Uppercase in doc

src/create-view-model.ts, test/create-view-model.js
Fixed issue #171
Fixed issue #173
=> [CreateViewModel] - Add changedValues computed

src/create-transformer.ts, test/create-transformer.ts
=> [CreateTransformer] - Add debugging name

src/create-view-model.ts, test/create-view-model.ts
=> [CreateViewModel] - Add changedValues to interface

src/create-view-model.ts
I ran into a typing issue when inspecting `changedValues` because it's currently typed as `Map<any, any>` and doesn't reflect the keys and values of the model being wrapped by the ViewModel.
After this change, the compiled interfaces are:
```typescript
export interface IViewModel<T> {
model: T;
reset(): void;
submit(): void;
isDirty: boolean;
changedValues: Map<keyof T, T[keyof T]>;
isPropertyDirty(key: keyof T): boolean;
resetProperty(key: keyof T): void;
}
export declare class ViewModel<T> implements IViewModel<T> {
model: T;
localValues: ObservableMap<keyof T, T[keyof T]>;
localComputedValues: ObservableMap<keyof T, IComputedValue<T[keyof T]>>;
readonly isDirty: boolean;
readonly changedValues: Map<keyof T, T[keyof T]>;
constructor(model: T);
isPropertyDirty: (key: keyof T) => boolean; …
```
=> ViewModel: local and computed values should have the same types as model

src/computedFn.ts, test/computedFn.ts
https://github.com/mobxjs/mobx/issues/2116
=> Supports IComputedOptions in computedFn

src/from-promise.ts
=> Fix docs of fromPromise

package.json
Module bundling hoist side effects in one file and webpack cannot tree shake it
=> Fix tree shaking

CHANGELOG.md, src/action-async.ts
Fixed #239 for old node versions when not using typescript transpilation
=> fix action async

CHANGELOG.md, src/action-async.ts, test/action-async.ts
=> fix action async execution order when throwing

src/ObservableGroupMap.ts, test/ObservableGroupMap.test.ts
Finish renaming from c13110ff6635cd3306b2d5bb30e1e9223cad3c9c.
Fixes #255
=> Fix ObservableGroupMap index out of bounds #255

src/ObservableGroupMap.ts, src/action-async.ts, src/computedFn.ts, src/create-transformer.ts, src/create-view-model.ts, src/deepMap.ts, src/deepObserve.ts, src/from-promise.ts, src/from-resource.ts, src/lazy-observable.ts, src/observable-stream.ts, src/tsconfig.json
src/tsconfig.json: set strict: true and fix errors
=> Enable TS strict mode

src/from-promise.ts, src/lazy-observable.ts, src/queue-processor.ts
Fix unused imports and sneak in a tiny typo fix.
=> Fix unused imports

README.md, src/ObservableGroupMap.ts
=> Don't attempt to polyfill Symbol, leave it up to the user.

src/create-view-model.ts, test/create-view-model.ts
=> fix(VM): Transparently handle computed setters

CHANGELOG.md, src/from-promise.ts, test/from-promise.js
=> fromPromise carries forward old value from pending observable

src/from-promise.ts
In `fromPromise`, we only assign fulfilled value to pending state, there is no reason that pending's `value` needs to be `unknown`. This PR corrects that.
It also makes the second parameter actually `IPromiseBasedObservable<T>` to match its real expectation, and removes unnecessary `as any` casting.
=> Give proper typing for fromPromise
