- README.md
- src/from-promise.ts
- test/from-promise.js
Let me know if there is something you dislike about the design or if I missed something or added too much of something 😀  (code / tests / docs / etc).
Some notes about this initial version:
* I made all handlers optional. This allows, for example, to add a loader/error indicator segment next to  dropdown component:
```jsx
promiseObs.case({
rejected: e => <ErrorIndicator tooltip={e.message} />, 
pending: () => <Loader />
})
```
There is nothing to be shown for the fulfilled case
* I considered using 3 different possible return types for the handlers and a union of them as the return result, but that didn't work out that well with optional handlers (the types always had `{}` in the union when a handler was left out). Settled on a single type - I think that would be the most common case. …
> Add case method to promise observable

- src/create-view-model.ts
- test/create-view-model.js
this PR adds `resetProperty(propName)` which allows to reset specified property. Plus it simplifiest the code quite a bit by omitting the `dirtyMap` variable and keeping track of dirtiness just by `localValues`
> [viewmodel] implemented resetProperty and simplifications

- src/lazy-observable.ts
- test/lazy-observable.js
lazyObserable sometimes need trigger to loading new data such as after edit profile, I need to run '/loadProfile' again
> add invalidating to lazyObservable

- .eslintrc
- .gitignore
- README.md
- package.json
- src/chunk-processor.ts
- src/create-view-model.ts
- src/from-promise.ts
- src/from-resource.ts
- src/lazy-observable.ts
- test/chunk-processor.js
- test/create-view-model.js
- test/from-promise.js
- test/from-resource.js
- test/guarded-when.js
- test/keep-alive.js
- test/lazy-observable.js
- test/queue-processor.js
- tslint.json
Add tslint support and eslint.
I don't use airbnb eslint, because it is for react application and es6.
I will use it in react-mobx.
> tslint and test refactoring

- src/lazy-observable.ts
- test/lazy-observable.js
In my case, I have a Tab component with two tabs (**Opening issues** and **Closed issues**). 
In each tab, we have a list of issues. Two tabs use only one lazyObservable instance. This instance fetch data from server base on the **state** flag of issue.
When user changes between tabs, we reset the lazyObservable instance to initial state. Then **current()** will fetch data again.
> add reset feature for lazyObservable

- src/create-view-model.ts
- test/observable-stream.js
'from Promise' throws a deprecation warning as well, but that one is not related to mobx3 so it wasn't updated.
> fix mobx3 deprecation warnings in npm run test

- src/observable-stream.ts
In the implementation of `StreamListener` for `fromStream`, the `complete()` handler (for a completed observable stream) [calls `this.subscription.unsubscribe()`][unsub].
Unfortunately, `this.subscription` is initialized with the line `this.subscription = observable.subscribe(this)` [in the constructor][sub].
This requires first evaluating `observable.subscribe(this)`, which calls the `complete()` handler if an already-completed observable was passed to it. As such, for already-completed observables, `fromStream` tries to call `.unsubscribe()` on `this.subscription` before it is initialized.
This fix simply doesn't try to unsubscribe if the complete handler fires before the subscription field has been initialized (is there any value in unsubscribing from a completed observable?)
Minimal …
> Fix fromStream to handle already completed streams

- src/create-view-model.ts
Hey,
I found problem with not bounded isPropertyDirty method and I've changed constructor method and added action.bound decorator to the method.
Error I had before after call that method: 
`Uncaught TypeError: Cannot read property 'localValues' of undefined`
Changed contructor to keep API stable.
> [createViewModel] Fix context for methods.

- CHANGELOG.md
- README.md
- package.json
- src/when-async.js
This PR adds an implementation of `whenAsync`, which is like normal `when`, except that this `when` will return a promise that resolves when the expression becomes truthy.
Feedback is greatly appreciated - I'm very excited to contribute to this project!
Closes #66
> Add whenAsync

- README.md
- src/from-promise.ts
- src/when-async.ts
- test/type-tests.ts
OK, trying this again with a fresh cut from `master`. I'm not sure what happened to `when-async.ts`, but I added it back into the `/src` folder and everything seems to be good now.
**Updates to `fromPromise` documentation:**
- Remove deprecated promise property from returned object.
- Document the returned object's compatibility with PromiseLike
- Add example of chaining additional handlers to the returned PromiseLike
> Update fromPromise documentation, rebuild README

- README.md
- src/array.ts
- src/mobx-utils.ts
- test/__snapshots__/array.ts.snap
- test/array.ts
Ripped from MobX with the deprecation warning removed.
> feat: add `moveItem` array utility

- src/create-view-model.ts
this is the fix for [issue#117: IViewModel is missing resetProperty(propName: string): void;](https://github.com/mobxjs/mobx-utils/issues/117)
> adding resetProperty to IViewModel

- README.md
Replace "sink" with "sync" in documentation of lazyObservable and fromResource.
Fixes #141
> Replace word "sink" with "sync" in documentation

- src/from-promise.ts
- test/from-promise.js
`fromPromise(promise, oldPromise?)`
While the new promise isn't resolved, the method will return the oldPromise value.
> Allow passing previous state to fromPromise

- src/create-transformer.ts
- test/__snapshots__/create-transformer.ts.snap
- test/create-transformer.ts
- yarn.lock
This would allow transformer to accept function as prop which may have custom properties.
> Allow memoization of function parameter

- src/create-view-model.ts
It is quite common pattern (at least in our projects) to have a non enumerable properties that use spread to access `this`. When createViewModel is used to create a view model of such object, the non-enumerability of the property is lost and usage if spread operator or Object.entries on `this` causes a cycle in the mobx computation. The small change here propagates the enumerability of the models' property to the newly created view model.
> Bugfix: createViewModel to honor the non-enumerability of a property

- README.md
- src/from-promise.ts
- test/from-promise.js
I saw a colleague writing something like this today:
```
const foo = fromPromise(fetchFoo());
const { bar, foobar } = foo.case({
fulfilled: value => value,
pending: value => ({ bar: "loading...", foobar: false }),
rejected: value => ({ bar: "error", foobar: false }),
});
```
This is basically fine, but the `value => value` just looked weird. This new argument gives you the option to rewrite the above into:
```
const foo = fromPromise(fetchFoo());
const { bar, foobar } = foo.case({
pending: value => ({ bar: "loading...", foobar: false }),
rejected: value => ({ bar: "error", foobar: false }),
}, true);
```
Sure, you need to know how the implementation works, but to me personally this feels like an improvement over having a function that only passes on what it receives.
> Add defaultFulfilled option to case

- src/lazy-observable.ts
- test/lazy-observable.js
At the first observable evaluation or when `refresh` is trigger, it must be awesome to know that a refresh action is performing.
This PR add a `pending` observable to a LazyObservable letting us know when a refresh action is running
> Add pending observable in lazyObservable

- src/deepObserve.ts
- test/deepObserve.ts
When deepObserve crawls through the target, `observeRecursively` verifies whether the `thing` it finds is an observable array, -object or -map prior to observing it and going deeper. This pull request applies the same check to `unobserveRecursively`.
I upgraded React Native in one of my projects earlier today. One of the changes was the addition of a 64-bit release variant on the Android side. I had overridden JSC to a different version some time ago, but that ended up not being included in the 64-bit binary of my app. It used whatever version RN 0.58 ships with.
I found out that code which previously worked fine no longer did. I have a store similar to:
````js
const userStore = observable({
models: observable.map(),
status: 'logged-out'
})
````
I then deeply observe changes to this …
> Fix: guard around unobserveRecursively to avoid error being thrown

- src/lazy-observable.ts
- test/lazy-observable.js
I am seeing a wired bug(or a feature, I am not 100% sure) where after I call lazyObservable.reset, lazyObservable ignores the fetch function and always return the initial value. I am not sure if that's expected but I would like to have lazyObservable continue to honor the fetch function after reset.
By setting started to false, the`current` function will call the fetch function when it's being invoked. I know this will be a breaking change but let me know what do you guys think.
> set started to false when calling lazyObservable.reset to allow further update to lazyObservable.

- src/create-view-model.ts
- src/utils.ts
- test/create-view-model.ts
This should fix the issues discussed here https://github.com/mobxjs/mobx-utils/issues/100#issuecomment-401765101
> Fix: ensure ES6 observable getters are included in createViewModel

- src/from-promise.ts
if you take a look at the readme, you'll see that the full example for `fromPromise` is not there. This fixes it
when this is merged and the docs are rebuilt, it will look like this https://github.com/vonovak/mobx-utils/tree/fixReadmePreview#examples
> fix readme appearance

- src/create-view-model.ts
My change in #169 was not accounting for the case that the property is not necessary an own property of the source object. Added a guard in similar way suggested by @mweststrate at https://github.com/mobxjs/mobx-utils/issues/191#issuecomment-487906280 
Sorry for the logic hiccup.
> Bugfix (issue-191): Add a guard for missing property descriptor when inheriting enumerable

- src/computedFn.ts
I notice that computedFn does not infer types from passed callback. I've been fix it, please review.
> Improve typings for computedFn

- README.md
Stumbled across a small typo with `fromPromise` in the README.
> Fix typo in README: `fromPromse` -> `fromPromise`

- src/from-promise.ts
Currently, attempting to access the stale value in the pending cause will throw
`Type '(staleValue: any) => Element' is not assignable to type '() => Element'`
> Fix IBasePromiseBasedObservable

- src/utils.ts
- test/create-view-model.ts
This attends to https://github.com/mobxjs/mobx-utils/issues/205
I've also removed Set which was causing IE11 and createViewModel not to work. I'm guessing there's a very small subset of people using Mobx/Mobx-Utils/createViewModel and IE11
> Fix: reinstate createViewModel unobserved properties

- CHANGELOG.md
- src/action-async.ts
- test/action-async.ts
Like the name, make task support plain values (like await does)
> add plain value support to task

- CHANGELOG.md
- src/action-async.ts
- test/action-async.ts
Fixes an issue where actionAsync would misbehave if no task was awaited inside.
Also improves the error message to give some more info while at it.
> fix actionAsync actions without task

- src/create-transformer.ts
- test/create-transformer.ts
In the same vein as #215, it would be great to use a custom equals
function with `createTransformer`, to avoid bubbling bubbling recomputes
of transformers that return arrays/maps/etc.
This commit passes the options through to the internal `computed`.  The
name option is not passed through, since that can be changed with
the `debugNameGenerator` option.
> Support IComputedOptions in createTransformer

- src/create-transformer.ts
- test/create-transformer.ts
> have transformer not memorize when called outside reactive context

- .vscode/launch.json
- CHANGELOG.md
- src/action-async.ts
- test/action-async.ts
Fixes #239 
Also fixes jest configuration to run unit tests in vscode
> Fix invalid `actionAsync` context when promises resolve at the same time in different actionAsync calls

- README.md
technically this is more accurate as fromPromise returns promise with some fields being already observable, so there's no need to wrap the whole return value in another observable
> add ref modifier to searchResults

- src/from-promise.ts
just like https://github.com/mobxjs/mobx-utils/pull/241 but it actually works - the previous PR was overwritten by publishing new version because readme is generated :D 
Since I modified just this one file it means the update will take effect after new release but I guess thats not a big deal
> add ref modifier to searchResults #2

- src/observable-stream.ts
- test/observable-stream.ts
@KEIII You're right, the initial value wasn't typed correctly. I changed your PR a bit, as it isn't necessary to add a second type parameter to type it properly. Could you check this resolves problems with your use case?
> Fix from stream initialvalue type

- src/ObservableGroupMap.ts
I was about to write similar type-improving implementations like `get()` for `entries()`, `values()`, and `forEach()` but then considered this would be a better approach.
> Improve public types by hiding GroupItem implementation detail.

- README.md
- src/ObservableGroupMap.ts
- src/from-promise.ts
- src/from-resource.ts
- src/lazy-observable.ts
- src/queue-processor.ts
ObservableGroupMap appeared twice in the Readme because the constructor of the class was documented. As recommended by https://github.com/documentationjs/documentation/blob/HEAD/docs/RECIPES.md#classes the constructor parameters should be documented in the class's documentation.
Regenerated Readme based on the current state using `yarn prepublishOnly`. Not sure why `lazyObservable ` and `fromResource` docs were removed. Can somebody explain?
> Move OGM constructor docs to class head.

- src/ObservableGroupMap.ts
> ObservableGroupMap: use deep:false when creating group arrays

- src/now.ts
- test/now.js
Fixes issue #271.
Solved by sink-ing the current time when the ticker is subscribed to. Added an unit test for good measure which currently fails on master.
> Fixed reused now() tickers initially returning old values (#271)

- src/computedFn.ts
Quite simple change. Unfortunately, I was unable to retrieve the name in a test, any suggestion is welcome.
> Use computedFn name if explicitly set in options

- src/from-promise.ts
This PR replaces `any` typing for observable promise's value field by `unknow`. `unknown` is the type-safe counterpart to `any`, so it should allow detecting unsafe branches in consumers code.
Typically before this change, this would pass type checking:
```ts
const observablePromise = fromPromise(Promise.resolve("a string"))
const aString: string = observablePromise.value
```
whereas with this change, one would need to write
```ts
const observablePromise = fromPromise(Promise.resolve("a string"))
if(observablePromise.state === "fulfilled") {
const aString: string = observablePromise.value
}
```
It is important to note that it will probably make some code that was compiling before failing since `any` was defacto disabling type checking.
This closes …
> Make observable promise's values safer type wise

- src/computedFn.ts
- test/computedFn.ts
This PR adds `onCleanup` callback to `computedFn` just like for `createTransformer`. In Canva we have a simplified version of `computedFnWithCleanup` (as some of the functionality in `computedFn` is provided by private functions).
> Add onCleanup for computedFn

- package.json
- src/from-promise.ts
- test/computedFn.ts
- test/create-transformer.ts
- test/deepObserve.ts
- test/expr.ts
- tsconfig.json
If you use mobx-utils in a TypeScript project with "strictNullChecks" enabled, you will find that no matter what you pass to `fromPromise.resolve()`, it always returns a type that contains `undefined`:
`IFulfilledPromise<T | undefined> & IBasePromiseBasedObservable<T>;`
This is frustrating because it forces you to check if the value is `undefined` before using it, even though you know it cannot be. The problem can be seen in `test/type-tests.ts` if you turn on "strictNullChecks":
* Enable "strictNullChecks", and use `preset: "ts-jest"`, to make sure that this TypeScript error is caught by the tests.
* Re-order the type overloads for `fromPromise.resolve` to fix the failing test.
> Fix fromPromise.resolve() returning undefined

- src/computedFn.ts
Addresses this issue: https://github.com/mobxjs/mobx-utils/issues/268
This will allow consumers to test code wrapped with `computedFn` easily by using 
```ts
mobx.configure({ computedRequiresReaction: false })
```
Currently in order to test a computed funciton you either:
1. Ignore the warnings, e.g. `--silent` in jest
2. Wrap the tested function in an `autorun` in each test or during setup before each test.
There will be a behavioural change in when a `computedFn` warning is triggered as the default for `computedRequiresReaction` is false. This will make it consistent in behaviour with the base `computed`, but if it is desirable to maintain the existing behavior we could add another option... I'm not sure where that would live, as mobx-utils has no global state and it seems odd to put …
> Update computedFn warning to respect mobx global computedRequiresReaction

- src/computedFn.ts
This PR fixes a typo (`an reactive context` -> `a reactive context`) in a console warning printed by `computedFn`.
> Fix a typo in the `computedFn` console warning

- README.md
I have to admit to a small gap in my understanding after reading the "create transformer in depth" section. After reading it, I totally missed the point that the function body of `createTransformer` also forms part of the reactive context (as opposed to just `A`) since the body is wrapped in computed ([here](https://github.com/mobxjs/mobx-utils/blob/master/src/create-transformer.ts#L75-L78)).
> docs: Minor update to createTransformer section

- src/create-transformer.ts
- test/create-transformer.ts
`createTransformer()` memoizes object transformations by creating a key for each possible input of type `A`, and then stores a mapping of that key to an object of type `B` in the context variable `views`. The key is stored on each `A` as a non-enumerable property named `$transformId`, so that each object can be looked up in the `views` cache later.
If we change `views` to be a `Map` instead of a plain object, we can get rid of the need for the IDs completely.
With this new impl, we still treat string and number inputs by value, and we still treat object inputs by identity. This comes down to the hashing semantics of Map.
This saves a small amount of memory in the unique memo IDs that were created for each input, and also some memory on each input object, which was modified to add the …
> Use a Map for createTransformer memoization
